# Generated by Django 6.0.3 on 2026-04-04 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('total_seats', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='students.faculty')),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('semester', models.IntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester'), (7, '7th Semester'), (8, '8th Semester')])),
                ('credits', models.IntegerField(default=3)),
                ('capacity', models.IntegerField(default=60)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('schedule', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to='students.faculty')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.department')),
            ],
            options={
                'ordering': ['department', 'code'],
                'unique_together': {('code', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('semester_year', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_marks', models.IntegerField(default=0, help_text='Out of 40')),
                ('external_marks', models.IntegerField(default=0, help_text='Out of 60')),
                ('total_marks', models.IntegerField(default=0, editable=False)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+ (90-100)'), ('A', 'A (80-89)'), ('B+', 'B+ (70-79)'), ('B', 'B (60-69)'), ('C', 'C (50-59)'), ('D', 'D (40-49)'), ('F', 'F (Below 40)')], max_length=3)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('released', models.BooleanField(default=False)),
                ('released_date', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='students.enrollment')),
            ],
            options={
                'ordering': ['-released_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_recorded', to='students.faculty')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.enrollment')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'ordering': ['-date'],
                'unique_together': {('enrollment', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('hostel', 'Hostel Fee'), ('exam', 'Exam Fee'), ('library', 'Library Fee'), ('activity', 'Activity Fee'), ('misc', 'Miscellaneous')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Paid'), ('paid', 'Fully Paid')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student')),
            ],
            options={
                'ordering': ['-due_date'],
                'unique_together': {('student', 'fee_type', 'semester', 'year')},
            },
        ),
    ]
