# Generated by Django 6.0.3 on 2026-04-04 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_department_course_enrollment_grade_attendance_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(default='Bachelor of Technology', max_length=100)),
                ('total_credits_required', models.IntegerField(default=120)),
                ('core_courses_required', models.IntegerField(default=30)),
                ('elective_courses_required', models.IntegerField(default=20)),
                ('core_courses_completed', models.IntegerField(default=0, editable=False)),
                ('elective_courses_completed', models.IntegerField(default=0, editable=False)),
                ('total_credits_earned', models.IntegerField(default=0, editable=False)),
                ('overall_progress', models.IntegerField(default=0, editable=False, help_text='Progress percentage')),
                ('expected_graduation', models.DateField(blank=True, null=True)),
                ('audit_status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('not_started', 'Not Started')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='degree_audit', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Degree Audits',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumulative_gpa', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4)),
                ('total_credits_completed', models.IntegerField(default=0, editable=False)),
                ('total_credits_attempted', models.IntegerField(default=0, editable=False)),
                ('total_courses_passed', models.IntegerField(default=0, editable=False)),
                ('total_courses_failed', models.IntegerField(default=0, editable=False)),
                ('cumulative_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('academic_standing', models.CharField(choices=[('Excellent', 'Excellent (GPA >= 3.7)'), ('Very Good', 'Very Good (GPA 3.4-3.69)'), ('Good', 'Good (GPA 3.0-3.39)'), ('Satisfactory', 'Satisfactory (GPA 2.0-2.99)'), ('Probation', 'Probation (GPA < 2.0)')], default='Good', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Transcripts',
                'ordering': ['-generated_date'],
            },
        ),
    ]
