# Generated by Django 6.0.3 on 2026-04-04 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_degreeaudit_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_courses_taught', models.IntegerField(default=0, editable=False)),
                ('current_semester_courses', models.IntegerField(default=0, editable=False)),
                ('total_students_taught', models.IntegerField(default=0, editable=False)),
                ('current_semester_students', models.IntegerField(default=0, editable=False)),
                ('average_class_gpa', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4)),
                ('average_grades_given', models.CharField(default='B', editable=False, help_text='Average letter grade', max_length=2)),
                ('student_satisfaction_score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('pass_rate_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('fail_rate_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('grade_a_count', models.IntegerField(default=0, editable=False)),
                ('grade_b_count', models.IntegerField(default=0, editable=False)),
                ('grade_c_count', models.IntegerField(default=0, editable=False)),
                ('grade_d_count', models.IntegerField(default=0, editable=False)),
                ('grade_f_count', models.IntegerField(default=0, editable=False)),
                ('total_credits_assigned', models.IntegerField(default=0, editable=False)),
                ('average_class_size', models.IntegerField(default=0, editable=False)),
                ('peak_semester_load', models.IntegerField(default=0, editable=False, help_text='Maximum credits in one semester')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_report', to='students.faculty')),
            ],
            options={
                'verbose_name_plural': 'Faculty Reports',
                'ordering': ['-last_updated'],
            },
        ),
    ]
