# Generated by Django 6.0.3 on 2026-04-04 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_facultyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('grade_released', 'Grade Released'), ('fee_due', 'Fee Due Soon'), ('fee_overdue', 'Fee Overdue'), ('enrollment_confirmed', 'Enrollment Confirmed'), ('enrollment_rejected', 'Enrollment Rejected'), ('attendance_warning', 'Attendance Warning'), ('academic_warning', 'Academic Warning'), ('transcript_available', 'Transcript Available'), ('report_generated', 'Report Generated'), ('system_notification', 'System Notification')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('email_sent', models.BooleanField(default=False)),
                ('email_failed', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.enrollment')),
                ('related_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.fee')),
                ('related_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.grade')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
